#!/bin/bash

## Where are the compiled tool-chain located?
TOOL_FOLDER=./build/bin/

## Where are the kmer files generated by Jellyfish?
RAW_KMER_FOLDER=./test/

## Where can we put some temporary files? (need write permission).
TEMP_FOLDER=./

## Where do we put the generated SeqOthelloMap? 

